module.exports = {
  schema: "./autogenerated/schema.graphql",
  documents: [
    "./graphql/operations/*.graphql",
    "./graphql/fragments/*.graphql",
  ],
  generates: {
    "./autogenerated/types.ts": {
      plugins: ["typescript"],
    },
    "./": {
      preset: "near-operation-file",
      presetConfig: {
        folder: "../../autogenerated/documents",
        baseTypesPath: "autogenerated/types.ts",
        extension: ".ts",
      },
      plugins: ["typescript-operations", "typed-document-node"],
      config: {
        documentMode: "documentNode",
        immutableTypes: false,
        enumsAsConst: true,
        namingConvention: {
          enumValues: "upper-case#upperCase",
        },
      },
    },
  },
};
