import * as types from "../resolvers";
import { makeSchema } from "nexus";
import { nexusPrisma } from "nexus-plugin-prisma";
import { join, resolve } from "path";

function resolvePath(path: string) {
  return resolve(process.cwd(), path);
}

export const schema = makeSchema({
  types,
  plugins: [nexusPrisma({ experimentalCRUD: true })],
  prettierConfig: resolvePath(".prettierrc"),
  outputs: {
    schema: join(process.cwd(), "/autogenerated/schema.graphql"),
    typegen: join(process.cwd(), "/autogenerated/nexus.ts"),
  },
  features: {
    abstractTypeStrategies: {
      isTypeOf: true,
    },
  },
  contextType: {
    module: join(process.cwd(), "/graphql/context/index.ts"),
    export: "Context",
  },
  sourceTypes: {
    modules: [
      {
        module: resolvePath("node_modules/.prisma/client/index.d.ts"),
        alias: "prisma",
      },
    ],
  },
  shouldExitAfterGenerateArtifacts: process.argv.includes("--nexus-exit"),
});
