import Head from "next/head";
import { withGraphQL } from "graphql/urql";
import { useQuery } from "urql";

import { FilteredTasks, MainLayout } from "components";
import { GetTasksDocument } from "autogenerated/documents/getTasks";
import { useState } from "react";
import { ITask } from "interfaces";

const Tasks = () => {
  const [{ data, fetching, error }] = useQuery({ query: GetTasksDocument });
  const [search, setSearch] = useState<string>("");

  if (fetching) {
    return <h1>Loading...</h1>;
  }

  if (error) {
    return <h1>error</h1>;
  }

  const getTasks = data!.getTasks as unknown as ITask[];

  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="text-3xl font-bold underline pb-[10px]">Tasks page</h1>
      <input
        className="m-[10px] p-[10px] border-2 border-[#bdd0f1] rounded"
        value={search}
        placeholder="Search by Title"
        onChange={({ target }) => setSearch(target.value)}
      />
      <div className="flex flex-wrap">
        <FilteredTasks tasks={getTasks} search={search} />
      </div>
    </MainLayout>
  );
};

export default withGraphQL(Tasks);
