import { FcEmptyTrash } from "react-icons/fc";
import classNames from "classnames";
import { useMutation } from "urql";

import { Task as ITask } from "@prisma/client";
import { DeleteByIdDocument } from "autogenerated/documents/deleteById";
import { UpdateByIdDocument } from "autogenerated/documents/updateById";

export const Task = ({ content, title, finished, id }: ITask) => {
  const [, updateMutation] = useMutation(UpdateByIdDocument);
  const [, deleteMutation] = useMutation(DeleteByIdDocument);

  const handleChange: () => Promise<void> = async () => {
    try {
      await updateMutation({
        id,
        finished: !finished,
      });
    } catch (error) {
      console.log(error);
    }
  };

  const handleRemove = async () => {
    try {
      await deleteMutation({ id });
    } catch (error) {
      console.log(error);
    }
  };

  const blockStyle: string = classNames(
    "w-[200px] relative flex flex-col p-[10px] mb-[10px] items-center border-solid border-2 border-indigo-600 rounded mx-[10px]",
    { "bg-[#dce7f1]": finished }
  );

  return (
    <div className={blockStyle}>
      <input
        type="checkbox"
        checked={finished}
        onChange={handleChange}
        className="absolute right-[6px]"
      />
      <button
        className="absolute right-[6px] bottom-[7px]"
        onClick={handleRemove}
      >
        <FcEmptyTrash />
      </button>
      <h2 className="font-medium">{title}</h2>
      <p className="font-light">{content}</p>
    </div>
  );
};
