import type { NextPage } from "next";
import Head from "next/head";
import { MainLayout } from "../components";

const Home: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1 className="text-3xl font-bold underline">Home page</h1>
    </MainLayout>
  );
};

export default Home;
